### ISSUE TITLE
auth problem

### ISSUE THREAD

**Issue by bragarods** [Usama0121/ariadne-jwt#23]
Hi everyone,

No exactly an issue, but need help with setup.

Trying to get a new token from username and password and it keep returning as the credentials are not valid.

query

```graphql
mutation tokenAuth {
  tokenAuth(username:"foo@bar.com",
    password:"foorpass") {
    token
  }
}
```

error

```graphql
"stacktrace": [
            "Traceback (most recent call last):",
            "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/graphql/execution/execute.py\", line 617, in resolve_field",
            "    result = resolve_fn(source, info, **args)",
            "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ariadne_jwt/decorators.py\", line 89, in wrapper",
            "    raise exceptions.JSONWebTokenError(",
            "ariadne_jwt.exceptions.JSONWebTokenError: Please, enter valid credentials"
          ],
          "context": {
            "root": "None",
            "password": "'foorpass'",
            "kwargs": "{'username': 'foo@bar.com'}",
            "on_resolve": "<function tok...t 0x1190eda20>",
            "username": "None",
            "user": "None",
            "info": "GraphQLResolv... 0x103b9e9e0>)",
            "f": "<function res...t 0x104154550>"
          }
        }
      }
    }
  ]
```

I have a custom user model, but USERNAME_FIELD is set to be 'email' and running the lambda function (the one setting JWT_PAYLOAD_GET_USERNAME_HANDLER) by hand it's return 'email'.

I also tried to login in Django base application first, but with no luck, it's also not recognizing the logged user.

Can anyone help me understand what's going on?

**Comment by Usama0121** [comment]
Kindly refer to the example project
There might be something misconfigured in settings.py

Also, try with a new user

**Comment by bragarods** [comment]
Thanks for the tip!

I managed to get it working by declaring the following in my main scheme.graphql file:

```graphql
type Mutation {
    tokenAuth(email: String!, password:String!): TokenAuth
    verifyToken(token: String!): VerifyToken
    revokeToken(refresh_token: String): RevokeToken
}
```

Overriding the tokenAuth argument to match my USERNAME_FIELD does the job. Then I get some errors regarding ariadne_jwt.refresh_token import and decide to disable this feature in settings.
