### ISSUE TITLE
help required in customizing the tokenAuth

### ISSUE THREAD

**Issue by MeetChaudhari** [Usama0121/ariadne-jwt#25]
i am porting the django-graphql-auth into my project based on ariadne, i need some help in decorators as i need to use email for login instead of username

**Comment by Usama0121** [comment]
This is handled by a custom User Model by default you may refer to [settings](https://github.com/Usama0121/ariadne-jwt/blob/71e5dde6ed778678bd01691edb8ab5c55710b444/README.md?plain=1#L223)
