### ISSUE TITLE
Running Tests

### ISSUE THREAD

**Issue by patryk-tech** [Usama0121/ariadne-jwt#3]
Hey! Thanks for writing this; I am a huge fan of Ariadne, Django, and JWTs.

I would love to hack on this project a bit, but as I generally use `pytest`, I cannot for the life of me figure out how to run the unit tests.

I have tried in the root folder:

```bash
$ DJANGO_SETTINGS_MODULE=tests.settings python -m unittest # and got
EEEEEEEEEEEEEEEEE
======================================================================
ERROR: ariadne_jwt.refresh_token.admin (unittest.loader._FailedTest)
ImportError: Failed to import test module: ariadne_jwt.refresh_token.admin
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
======================================================================
ERROR: setUpClass (tests.refresh_token.test_commands.ClearTokensTests)
django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the NAME value.
```
and a total of 17 errors (all based on these two).

Adding `'NAME': ':memory:',` to `tests/settings.py` gets rid of the `ImproperlyConfigured`, but gives me 41 `AppRegistryNotReady` errors.

Could you let me know how to run those tests (or better yet, add that to the `README`)? Thanks!

PS: I have a number of ideas and suggestions. Is there a more direct way of communicating with you (e.g. discord) or would you prefer that I open issues for them?

**Comment by Usama0121** [comment]
You will need to run `run_tests.py` inside the tests directory
~~~sh
ariadne-jwt/tests$ python run_tests.py
~~~
I was using pycharm for running tests which by default sets paths to ariadne-jwt and tests directory
for now, just add the following to the main of `run_tests.py` to add the required paths
~~~py
if __name__ == '__main__':
    sys.path.append(os.path.join(os.curdir, '..', 'tests'))
    sys.path.append(os.path.join(os.curdir, '..'))
    .
    .
~~~

You may open issues for any ideas or discussion.

**Comment by Usama0121** [comment]
Just made some changes
Tests should now run from the root directory
~~~shell script
ariadne-jwt$ python run_tests.py
~~~

**Comment by trbhoang** [comment]
This is how I run from Django: 
`
$ ./manage.py test ./project.tests.run_tests
`
where run_test.py is placed in ./project/tests/

**Comment by Usama0121** [comment]
you don't need to run it with manage.py instead just execute `python run_tests.py`

**Comment by Usama0121** [comment]
Added [some tests](https://github.com/Usama0121/ariadne-jwt/commit/1713ecd37eba8283a925ba0f89fd3ba0225a910d) in the [example project](https://github.com/Usama0121/ariadne-jwt/tree/master/examples/project_1) for reference.

To run tests in a Django application run the following command
~~~python
python manage.py test
~~~
