### ISSUE TITLE
How do I change settings?

### ISSUE THREAD

**Issue by IgnisDa** [Usama0121/ariadne-jwt#7]
I would like to change the default JWT expiration time, but I can't find anything in the documentation to do it. Additionally, the `settings.py` for this package doesn't really expose anything to change settings conveniently. Am I missing something here or is this a feature that has not been implemented yet?

**Comment by Usama0121** [comment]
Add the following in Django settings.py

~~~python
GRAPHQL_JWT = {
    'JWT_VERIFY_EXPIRATION': True,
    'JWT_EXPIRATION_DELTA': timedelta(seconds=60 * 10)
}
~~~

**Comment by IgnisDa** [comment]
Thank you very much. I'll close the issue since it has been resolved.

**Comment by IgnisDa** [comment]
I suppose this package hasn't been updated with these changes in the PyPI? Could you please do it?

**Comment by Usama0121** [comment]
Just Released a new version of the library. Closing the issue.
